import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, ArrowUpRight } from "lucide-react";
import { getActiveDepartments, getPublicRows } from "@/lib/content";
import type { ContentRow } from "@/lib/content";

const content: Record<string, { title: string; eyebrow: string; intro: string; heading: string; paragraphs: string[]; cards: [string,string][] }> = {
  faculty: { title: "The Faculty", eyebrow: "Our story & purpose", intro: "A community committed to scientific education, research and service at the University of Yaoundé I.", heading: "Science in service of society.", paragraphs: ["The Faculty of Science is part of the University of Yaoundé I, a leading public institution for higher education and research in Cameroon. Across our departments, students learn to question, investigate and apply scientific ideas with care and imagination.", "Our work is grounded in academic integrity, intellectual openness and a belief that scientific knowledge can contribute to a more sustainable and thriving society. Faculty life brings together teaching, research and meaningful engagement with our wider community."], cards: [["Our mission", "Deliver rigorous, relevant science education and advance research that responds to local and global challenges."],["Our vision", "A welcoming and internationally connected centre of scientific learning, discovery and public service."],["Our values", "Curiosity, integrity, excellence, collaboration and respect for the diversity of our community."],["Our home", "Located at the Ngoa-Ekellé campus of the University of Yaoundé I in Cameroon." ]] },
  departments: { title: "Departments", eyebrow: "Explore our disciplines", intro: "Six departments create a rich, connected environment for scientific study and discovery.", heading: "Find your field of inquiry.", paragraphs: ["Our departments provide focused academic communities, specialist teaching and opportunities to participate in research. Select an area to explore its programmes, people and research interests.", "Department profiles and contacts are being prepared for publication by faculty administrators. Check back for updates."], cards: [["Biological Sciences", "Life sciences, biodiversity, ecology and molecular research."],["Chemistry", "Chemical sciences, materials and analytical methods."],["Computer Science", "Computing, data, software and digital systems."],["Earth Sciences", "Geology, geophysics, environment and natural resources."],["Mathematics", "Pure and applied mathematics, statistics and modelling."],["Physics", "Fundamental and applied physics, matter and energy."]] },
  programs: { title: "Academic programmes", eyebrow: "Study science", intro: "Explore pathways across departments, from foundational study to advanced specialisation.", heading: "Build your scientific future.", paragraphs: ["Academic programmes are organised by department and level. Programme structures and course information are maintained by faculty staff and will be published here as they are verified.", "For admissions requirements, deadlines and official information, please contact the relevant department or consult the University of Yaoundé I admissions office."], cards: [["Undergraduate", "Foundational and specialist study pathways across the sciences."],["Graduate study", "Advanced academic programmes and research-led learning."],["Academic calendar", "Key dates and official documents for the current academic year."],["Student resources", "Guidance and forms for students in the Faculty of Science."]] },
  research: { title: "Research & innovation", eyebrow: "Investigate the unknown", intro: "Research across our faculty explores the natural world, develops new methods and responds to the needs of our communities.", heading: "Questions worth pursuing.", paragraphs: ["Our researchers work across disciplinary boundaries, from biological diversity and public health to computational methods, materials, mathematical modelling and earth systems.", "Research profiles, projects, laboratories and publications are managed through the faculty's content system. Published information will appear here as it is verified and made available."], cards: [["Research areas", "Discover the themes and questions guiding research across our departments."],["Projects", "Explore active projects, collaborations and opportunities to participate."],["Laboratories", "Meet the teams and facilities supporting scientific investigation."],["Research with us", "Connect with faculty researchers and learn about collaboration."]] },
  news: { title: "News from the Faculty", eyebrow: "Ideas & announcements", intro: "Stories, announcements and achievements from our academic community.", heading: "What’s happening here.", paragraphs: ["Faculty news brings together verified announcements from departments, research teams and the wider University community.", "News articles will be published here by authorised faculty administrators."], cards: [["Admissions", "Official admissions notices and important application information."],["Research", "Discoveries, publications and updates from our researchers."],["Faculty life", "People, partnerships and activities across our campus."]] },
  "news-events": { title: "News & Events", eyebrow: "Faculty updates and events", intro: "News, announcements, seminars and events from across the Faculty of Science.", heading: "Across the Faculty.", paragraphs: ["Follow news and upcoming events from departments, research teams and the wider Faculty community.", "Choose a story or event to read its full details."], cards: [] },
  events: { title: "Events & academic dates", eyebrow: "Meet, learn, share", intro: "Lectures, seminars, workshops and events for the Faculty of Science community.", heading: "Make room for discovery.", paragraphs: ["Join talks, academic gatherings and community events across the faculty. Event details are maintained by authorised faculty staff.", "Dates shown on this site should be confirmed with the organising department before making travel arrangements."], cards: [["Seminars", "Ideas and findings shared by local and visiting researchers."],["Workshops", "Practical learning and exchange across scientific fields."],["Academic calendar", "Key semester dates and official university activities."]] },
  gallery: { title: "Faculty gallery", eyebrow: "Life at the Faculty", intro: "A glimpse into teaching, research and community across the Faculty of Science.", heading: "Moments of discovery.", paragraphs: ["Images are shared to celebrate the people, places and activities that make our faculty community. All media is curated by faculty staff.", "The gallery will grow as approved photographs are added to the faculty's media library."], cards: [["In the lab", "Research and practical learning across our scientific disciplines."],["On campus", "Spaces, events and everyday moments at Ngoa-Ekellé."],["Our community", "Students, staff and collaborators learning together."]] },
  documents: { title: "Documents & resources", eyebrow: "Useful information", intro: "Find public academic calendars, student guides, forms and official faculty notices.", heading: "The information you need.", paragraphs: ["Documents published here are intended for public access. Always check the issue date and consult your department if you are unsure whether a document is current.", "Official files will be uploaded and managed by authorised faculty administrators. No confidential student or staff documents are published in this library."], cards: [["Academic calendars", "Semester dates, registration windows and university activities."],["Student guides", "Public guidance for academic life and study at the faculty."],["Forms & regulations", "Approved forms, policies and faculty regulations."],["Notices", "Public announcements and important information."]] },
  contact: { title: "Contact the Faculty", eyebrow: "We are here to help", intro: "Contact the Faculty of Science at the University of Yaoundé I.", heading: "Start a conversation.", paragraphs: ["For programme, course and timetable questions, please contact the relevant department. For admissions and general university matters, consult the University of Yaoundé I's official channels.", "The details below are institutional contact information and should be confirmed by the faculty administration before production launch."], cards: [["Visit us", "Ngoa-Ekellé campus, Yaoundé, Cameroon."],["Email", "facsciences@uy1.uninet.cm"],["Telephone", "+237 222 23 44 96"],["Office hours", "Monday to Friday · 08:00–15:30 (confirm locally)."]] },
};

export const dynamic = "force-dynamic";
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> { const { slug } = await params; return { title: content[slug]?.title ?? "Faculty information", description: content[slug]?.intro }; }
const tableByPage: Record<string, string> = { programs: "programs", research: "research_projects", news: "news", events: "events", gallery: "gallery_items", documents: "documents" };
function rowTitle(row: ContentRow, page: string) { return page === "programs" ? row.name : page === "research" ? row.title : row.title; }
function rowDescription(row: ContentRow, page: string) { return page === "programs" ? `${row.degree}${row.level ? ` · ${row.level}` : ""} ${row.description ?? ""}` : page === "research" ? row.summary : row.excerpt ?? row.description ?? row.category ?? ""; }
function rowHref(row: ContentRow, page: string) { if (page === "documents" && row.storage_path) return row.storage_path; return row.slug ? `/${page}/${row.slug}` : `/${page}`; }
export default async function InformationPage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params; const page = content[slug];
  if (!page) return <div className="page-hero"><div className="wrap"><p className="section-kicker">Page not found</p><h1>That page isn’t here.</h1><Link className="text-link" href="/">Return home <ArrowRight size={15}/></Link></div></div>;
  const departments = slug === "departments" ? await getActiveDepartments() : [];
  const rows = tableByPage[slug] ? await getPublicRows(tableByPage[slug]) : [];
  const combined = slug === "news-events" ? (await Promise.all([getPublicRows("news"), getPublicRows("events")])).flatMap((items,i)=>items.map(row=>({...row,_kind:i===0?"News":"Event",_href:i===0?`/news/${row.slug}`:`/events/${row.slug}`,_date:row.published_at||row.starts_at}))).sort((a,b)=>String(b._date??"").localeCompare(String(a._date??""))) : [];
  const list = slug === "departments" ? departments : slug === "news-events" ? combined : rows;
  return <><section className="page-hero"><div className="wrap"><p className="section-kicker">{page.eyebrow}</p><h1>{page.title}</h1><p>{page.intro}</p></div></section><section className="content-section"><div className="wrap"><div className="content-block"><h2>{page.heading}</h2>{page.paragraphs.map((p)=><p key={p}>{p}</p>)}</div>
  {slug === "news-events" ? <div className="resource-grid">{combined.length?combined.map((row:any)=><article className="resource-card" key={`${row._kind}-${row.id}`}>{row.image_path&&<img src={row.image_path} alt={row.title}/>}<p className="section-kicker">{row._kind}{row.department?.name?` · ${row.department.name}`:" · Faculty-wide"}</p><h2><Link href={row._href}>{row.title}</Link></h2><p>{row.excerpt||row.description}</p></article>):<p className="empty-inline">Faculty news and events will appear here when published.</p>}</div> : slug === "departments" ? <div className="card-grid">{departments.map((row:ContentRow,index:number)=><Link className="dept-card" href={`/departments/${row.slug}`} key={row.slug}><span className="card-number">DEPARTMENT {String(index+1).padStart(2,"0")}</span><h3>{row.name}</h3><p>{row.description}</p><span className="card-arrow"><ArrowUpRight size={17}/></span></Link>)}</div> : list.length ? <div className="resource-grid">{list.map((row: ContentRow) => {const title = rowTitle(row, slug); const description = slug === "departments" ? row.description : rowDescription(row, slug); const href = slug === "departments" ? `/departments/${row.slug}` : slug === "gallery" ? (row.related_event?.slug ? `/events/${row.related_event.slug}` : row.related_research?.slug ? `/research/${row.related_research.slug}` : row.specialty?.slug && row.department?.slug ? `/departments/${row.department.slug}/specialties/${row.specialty.slug}` : row.department?.slug ? `/departments/${row.department.slug}` : "/gallery") : rowHref(row, slug); const external = slug === "documents"; return <article className="resource-card" key={row.id}><div>{slug === "gallery" && row.image_path && <img src={row.image_path} alt={row.title} />}</div><p className="section-kicker">{slug === "departments" ? "Department" : row.category ?? page.eyebrow}</p><h2><Link href={href} target={external ? "_blank" : undefined} rel={external ? "noreferrer" : undefined}>{title}</Link></h2><p>{description}</p>{slug === "gallery" && (row.related_event||row.related_research) && <p className="resource-context">{row.related_event?.title ?? row.related_research?.title}</p>}{row.department?.name&&<p className="resource-context">{row.department.name}{row.specialty?.name?` · ${row.specialty.name}`:""}</p>}<Link className="text-link" href={href} target={external ? "_blank" : undefined} rel={external ? "noreferrer" : undefined}>{external ? "Open resource" : "Explore"} <ArrowUpRight size={14}/></Link></article>})}</div> : <div className="simple-list">{page.cards.map(([title,desc])=><article key={title}><h3>{title}</h3><p>{desc}</p></article>)}</div>}
  {slug === "contact" && <p style={{marginTop:25}}><Link className="text-link" href="mailto:facsciences@uy1.uninet.cm">Email the Faculty <ArrowUpRight size={15}/></Link></p>}</div></section></>;
}
