import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowLeft, ArrowUpRight } from "lucide-react";
import { createPublicClient } from "@/lib/supabase/public";

export const dynamic = "force-dynamic";
const tables:Record<string,{table:string;title:(row:any)=>string;body:(row:any)=>string}>={news:{table:"news",title:(x)=>x.title,body:(x)=>x.body||x.excerpt},events:{table:"events",title:(x)=>x.title,body:(x)=>x.description},programs:{table:"programs",title:(x)=>x.name,body:(x)=>x.details||x.description},research:{table:"research_projects",title:(x)=>x.title,body:(x)=>x.details||x.summary}};
export async function generateMetadata({params}:{params:Promise<{section:string;slug:string}>}){const {section,slug}=await params;const config=tables[section];const client=createPublicClient();if(!config||!client)return {title:"Faculty information"};const {data}=await client.from(config.table).select("*").eq("slug",slug).maybeSingle();return {title:data?config.title(data):"Faculty information"};}
export default async function ContentDetail({params}:{params:Promise<{section:string;slug:string}>}){
 const {section,slug}=await params;const config=tables[section];const client=createPublicClient();if(!config||!client)notFound();
 const detailQuery=client.from(config.table).select("*").eq("slug",slug);
 const {data:item}=section==="programs"?await detailQuery.eq("is_active",true).maybeSingle():await detailQuery.eq("status","published").maybeSingle();if(!item)notFound();
 let department:any=null,specialty:any=null;
 if(item.department_id){const result=await client.from("departments").select("name,slug").eq("id",item.department_id).maybeSingle();department=result.data;}
 if(item.specialization_id){const result=await client.from("specializations").select("name,slug,department_id").eq("id",item.specialization_id).maybeSingle();specialty=result.data;if(!department&&specialty?.department_id){const dept=await client.from("departments").select("name,slug").eq("id",specialty.department_id).maybeSingle();department=dept.data;}}
 const [relatedGallery,relatedDocuments]=await Promise.all([
   section==="events"?client.from("gallery_items").select("id,title,description,image_path").eq("event_id",item.id).eq("status","published"):section==="research"?client.from("gallery_items").select("id,title,description,image_path").eq("research_project_id",item.id).eq("status","published"):Promise.resolve({data:[]}),
   section==="programs"?client.from("documents").select("id,title,description,storage_path").eq("program_id",item.id).eq("status","published"):section==="research"?client.from("documents").select("id,title,description,storage_path").eq("research_project_id",item.id).eq("status","published"):Promise.resolve({data:[]}),
 ]);
 const date=item.published_at||item.starts_at||item.created_at;
 return <><section className="page-hero"><div className="wrap"><p className="section-kicker">{section} {department&&<>· <Link href={`/departments/${department.slug}`}>{department.name}</Link></>}{specialty&&<> · {specialty.name}</>}{date&&<> · {new Date(date).toLocaleDateString("en",{dateStyle:"long"})}</>}</p><h1>{config.title(item)}</h1><p>{item.excerpt||item.summary||item.degree||"Faculty of Science · University of Yaoundé I"}</p></div></section><section className="content-section"><article className="wrap detail-layout"><div className="content-block"><h2>Overview</h2><p className="detail-body">{config.body(item)}</p>{item.lead_name&&<p><strong>Research lead:</strong> {item.lead_name}</p>}{item.starts_at&&<p><strong>Starts:</strong> {new Date(item.starts_at).toLocaleString("en",{dateStyle:"long",timeStyle:"short"})}{item.location?` · ${item.location}`:""}</p>}</div><aside className="detail-context"><p className="section-kicker">Content context</p><div className="hierarchy-trail"><span>FACULTY</span>{department&&<><span>→</span><Link href={`/departments/${department.slug}`}>{department.name}</Link></>}{specialty&&<><span>→</span><Link href={`/departments/${department.slug}/specialties/${specialty.slug}`}>{specialty.name}</Link></>}</div>{item.image_path&&<img className="detail-image" src={item.image_path} alt=""/>}{item.storage_path&&<a className="text-link" href={item.storage_path} target="_blank" rel="noreferrer">Open resource <ArrowUpRight size={14}/></a>}</aside>{relatedGallery.data?.length ? <section className="detail-related"><p className="section-kicker">Related gallery</p><div className="resource-grid">{relatedGallery.data.map((image:any)=><article className="resource-card" key={image.id}>{image.image_path&&<img src={image.image_path} alt={image.title}/>}<h2>{image.title}</h2><p>{image.description}</p></article>)}</div></section> : null}{relatedDocuments.data?.length ? <section className="detail-related"><p className="section-kicker">Related documentation</p><div className="simple-list">{relatedDocuments.data.map((doc:any)=><article key={doc.id}><h3><a href={doc.storage_path} target="_blank" rel="noreferrer">{doc.title}</a></h3><p>{doc.description}</p></article>)}</div></section> : null}<Link className="text-link" href={`/${section}`}><ArrowLeft size={14}/> Back to {section}</Link></article></section></>;
}
