"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { createClient } from "@/lib/supabase/client";
import { ArrowUpRight, Check, ChevronRight, Eye, FilePlus2, FolderTree, LayoutDashboard, LoaderCircle, Search, Trash2 } from "lucide-react";
import { toSlug } from "@/lib/content";

type Field = { key:string; label:string; kind?:"text"|"textarea"|"number"|"date"|"datetime"|"select"|"boolean"; options?:string[]; relation?:"departments"|"specializations"|"programs"|"events"|"research_projects"|"timetables"; required?:boolean };
type Module = { key:string; label:string; table:string; route:string; titleField:string; fields:Field[]; context?:"department"|"specialty"; status?:boolean };
const statusOptions=["draft","published","archived"];
const modules:Module[]=[
 {key:"faculty",label:"Faculty information",table:"faculty_information",route:"/about",titleField:"title",fields:[{key:"key",label:"Content key",required:true},{key:"title",label:"Title",required:true},{key:"content",label:"Content (JSON)",kind:"textarea"},{key:"is_public",label:"Public",kind:"boolean"}]},
 {key:"departments",label:"Departments",table:"departments",route:"/departments",titleField:"name",fields:[{key:"name",label:"Department name",required:true},{key:"slug",label:"URL slug"},{key:"description",label:"Presentation",kind:"textarea"},{key:"image_path",label:"Department image"},{key:"mission",label:"Mission",kind:"textarea"},{key:"vision",label:"Vision",kind:"textarea"},{key:"objectives",label:"Objectives",kind:"textarea"},{key:"teaching_areas",label:"Teaching areas (comma separated)"},{key:"research_areas",label:"Research areas (comma separated)"},{key:"head_name",label:"Head of department"},{key:"contact_email",label:"Contact email"},{key:"is_active",label:"Active",kind:"boolean"},{key:"sort_order",label:"Display order",kind:"number"}]},
 {key:"specializations",label:"Specialties",table:"specializations",route:"/departments",titleField:"name",context:"department",fields:[{key:"department_id",label:"Department",relation:"departments",required:true},{key:"name",label:"Specialty name",required:true},{key:"slug",label:"URL slug"},{key:"description",label:"Presentation",kind:"textarea"},{key:"image_path",label:"Specialty image"},{key:"mission",label:"Mission",kind:"textarea"},{key:"teaching_areas",label:"Teaching areas (comma separated)"},{key:"research_areas",label:"Research areas (comma separated)"},{key:"is_active",label:"Active",kind:"boolean"},{key:"sort_order",label:"Display order",kind:"number"}]},
 {key:"programs",label:"Programmes",table:"programs",route:"/programs",titleField:"name",context:"department",fields:[{key:"department_id",label:"Department",relation:"departments",required:true},{key:"specialization_id",label:"Specialty",relation:"specializations"},{key:"name",label:"Programme name",required:true},{key:"slug",label:"URL slug"},{key:"degree",label:"Degree",required:true},{key:"level",label:"Level"},{key:"academic_year",label:"Academic period"},{key:"description",label:"Short description",kind:"textarea"},{key:"details",label:"Programme details",kind:"textarea"},{key:"image_path",label:"Programme image"},{key:"is_active",label:"Active",kind:"boolean"}]},
 {key:"research",label:"Research projects",table:"research_projects",route:"/research",titleField:"title",context:"department",status:true,fields:[{key:"department_id",label:"Department",relation:"departments"},{key:"specialization_id",label:"Specialty",relation:"specializations"},{key:"title",label:"Project title",required:true},{key:"slug",label:"URL slug"},{key:"summary",label:"Summary",kind:"textarea"},{key:"details",label:"Research details",kind:"textarea"},{key:"lead_name",label:"Lead researcher"},{key:"team_name",label:"Research team"},{key:"image_path",label:"Image URL"},{key:"starts_on",label:"Start date",kind:"date"},{key:"ends_on",label:"End date",kind:"date"},{key:"status",label:"Publication status",kind:"select",options:statusOptions}]},
 {key:"news",label:"News",table:"news",route:"/news",titleField:"title",context:"department",status:true,fields:[{key:"department_id",label:"Department",relation:"departments"},{key:"specialization_id",label:"Specialty",relation:"specializations"},{key:"title",label:"Headline",required:true},{key:"slug",label:"URL slug"},{key:"excerpt",label:"Excerpt",kind:"textarea"},{key:"body",label:"Article body",kind:"textarea"},{key:"author_name",label:"Author"},{key:"image_path",label:"Image URL"},{key:"status",label:"Publication status",kind:"select",options:statusOptions},{key:"published_at",label:"Publish date",kind:"datetime"}]},
 {key:"events",label:"Events",table:"events",route:"/events",titleField:"title",context:"department",status:true,fields:[{key:"department_id",label:"Department",relation:"departments"},{key:"specialization_id",label:"Specialty",relation:"specializations"},{key:"title",label:"Event title",required:true},{key:"slug",label:"URL slug"},{key:"description",label:"Description",kind:"textarea"},{key:"starts_at",label:"Starts at",kind:"datetime",required:true},{key:"ends_at",label:"Ends at",kind:"datetime"},{key:"location",label:"Location"},{key:"image_path",label:"Image URL"},{key:"status",label:"Publication status",kind:"select",options:["draft","published","cancelled"]}]},
 {key:"gallery",label:"Gallery",table:"gallery_items",route:"/gallery",titleField:"title",context:"department",status:true,fields:[{key:"department_id",label:"Department",relation:"departments"},{key:"specialization_id",label:"Specialty",relation:"specializations"},{key:"event_id",label:"Related event",relation:"events"},{key:"research_project_id",label:"Related research",relation:"research_projects"},{key:"title",label:"Image title",required:true},{key:"description",label:"Description",kind:"textarea"},{key:"category",label:"Category"},{key:"image_path",label:"Image URL",required:true},{key:"is_featured",label:"Featured",kind:"boolean"},{key:"status",label:"Publication status",kind:"select",options:["draft","published"]}]},
 {key:"documents",label:"Documentation",table:"documents",route:"/documents",titleField:"title",context:"department",status:true,fields:[{key:"department_id",label:"Department",relation:"departments"},{key:"specialization_id",label:"Specialty",relation:"specializations"},{key:"program_id",label:"Programme",relation:"programs"},{key:"research_project_id",label:"Research project",relation:"research_projects"},{key:"title",label:"Document title",required:true},{key:"description",label:"Description",kind:"textarea"},{key:"category",label:"Category"},{key:"academic_level",label:"Academic level"},{key:"storage_path",label:"Public file URL or storage path",required:true},{key:"mime_type",label:"MIME type",required:true},{key:"file_size_bytes",label:"File size in bytes",kind:"number",required:true},{key:"status",label:"Publication status",kind:"select",options:["draft","published"]},{key:"published_at",label:"Publish date",kind:"datetime"}]},
 {key:"timetables",label:"Timetables",table:"timetables",route:"/timetables",titleField:"level",context:"department",status:true,fields:[{key:"department_id",label:"Department",relation:"departments",required:true},{key:"specialization_id",label:"Specialty",relation:"specializations"},{key:"program_id",label:"Programme",relation:"programs",required:true},{key:"level",label:"Level",required:true},{key:"semester",label:"Semester / period",required:true},{key:"academic_year",label:"Academic year",required:true},{key:"status",label:"Publication status",kind:"select",options:statusOptions},{key:"published_at",label:"Publish date",kind:"datetime"}]},
 {key:"timetable_entries",label:"Timetable classes",table:"timetable_entries",route:"/timetables",titleField:"course_name",context:"department",fields:[{key:"timetable_id",label:"Timetable",relation:"timetables",required:true},{key:"course_name",label:"Course",required:true},{key:"teacher",label:"Teacher"},{key:"room",label:"Room"},{key:"day_of_week",label:"Day (1 Monday – 6 Saturday)",kind:"number",required:true},{key:"start_time",label:"Start time",required:true},{key:"end_time",label:"End time",required:true}]},
];
const relationLabels:Record<string,string>={departments:"name",specializations:"name",programs:"name",events:"title",research_projects:"title",timetables:"level"};
const slugFields=new Set(["programs","research_projects","news","events"]);

export function AdminWorkspace({displayName}:{displayName:string}) {
 const client=useMemo(()=>createClient(),[]);
 const [active,setActive]=useState("departments"),[rows,setRows]=useState<any[]>([]),[relations,setRelations]=useState<Record<string,any[]>>({}),[departments,setDepartments]=useState<any[]>([]),[specialties,setSpecialties]=useState<any[]>([]);
 const [departmentId,setDepartmentId]=useState(""),[specialtyId,setSpecialtyId]=useState(""),[search,setSearch]=useState(""),[globalSearch,setGlobalSearch]=useState(false),[globalRows,setGlobalRows]=useState<any[]>([]),[editing,setEditing]=useState<any|null>(null),[draft,setDraft]=useState<Record<string,any>>({}),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[notice,setNotice]=useState("");
 const module=modules.find(x=>x.key===active)!;
 const setValue=(key:string,value:any)=>setDraft(prev=>({...prev,[key]:value}));
 useEffect(()=>{
   if(!client||!globalSearch||!search.trim()){setGlobalRows([]);return;}
   let cancelled=false;
   const timer=window.setTimeout(()=>{Promise.all(modules.map(async m=>{const select=m.key==="timetable_entries"?"*,timetable:timetables(id,department_id,specialization_id,level,semester,academic_year)":"*";const {data}=await client.from(m.table as any).select(select).limit(150);return (data??[]).filter((row:any)=>JSON.stringify(row).toLowerCase().includes(search.toLowerCase())).map((row:any)=>({...row,_moduleKey:m.key}));})).then(all=>{if(!cancelled)setGlobalRows(all.flat().slice(0,100));});},220);
   return ()=>{cancelled=true;window.clearTimeout(timer);};
 },[client,globalSearch,search]);
 const loadRelations=useCallback(async()=>{
   if(!client)return;
   const wanted=[...new Set(modules.flatMap(m=>m.fields.map(f=>f.relation).filter(Boolean) as string[]))];
   const result:Record<string,any[]>={};
   await Promise.all(wanted.map(async table=>{const {data}=await client.from(table as any).select("*").order("created_at",{ascending:false}).limit(200);result[table]=data??[];}));
   setRelations(result);setDepartments(result.departments??[]);setSpecialties(result.specializations??[]);
 },[client]);
 const loadRows=useCallback(async()=>{
   if(!client){setLoading(false);setNotice("Supabase is not configured.");return;}
   setLoading(true);setNotice("");
   const select=module.key==="timetable_entries"?"*,timetable:timetables(id,department_id,specialization_id,level,semester,academic_year)":"*";
   const {data,error}=await client.from(module.table as any).select(select).order(module.table==="faculty_information"?"updated_at":"created_at",{ascending:false}).limit(300);
   if(error){setRows([]);setNotice(`Cannot load ${module.label.toLowerCase()}. Apply the latest Supabase migration and check admin access. ${error.message}`);}
   else setRows(data??[]);
   setLoading(false);
 },[client,module]);
 useEffect(()=>{void loadRelations();},[loadRelations]);
 useEffect(()=>{void loadRows();setEditing(null);setDraft({});},[loadRows]);
 const scopedRows=useMemo(()=>rows.filter(row=>{
   const rowDepartment=row.department_id??row.timetable?.department_id;
   const rowSpecialty=row.specialization_id??row.timetable?.specialization_id;
   if(departmentId&&rowDepartment&&rowDepartment!==departmentId)return false;
   if(specialtyId&&rowSpecialty&&rowSpecialty!==specialtyId)return false;
   if(search&&!JSON.stringify(row).toLowerCase().includes(search.toLowerCase()))return false;
   return true;
 }),[rows,departmentId,specialtyId,search]);
 const createRecord=()=>{setEditing({});const values=module.fields.reduce((a,f)=>({...a,[f.key]:f.kind==="boolean"?false:f.kind==="select"?(f.options?.[0]??""):""}),{} as Record<string,any>);if(module.fields.some(f=>f.key==="department_id"))values.department_id=departmentId||"";if(module.fields.some(f=>f.key==="specialization_id"))values.specialization_id=specialtyId||"";setDraft(values);setNotice("");};
 const editRecord=(row:any,target:Module=module)=>{setActive(target.key);setEditing(row);const values={...row};for(const f of target.fields){if((f.kind==="date"||f.kind==="datetime")&&values[f.key])values[f.key]=String(values[f.key]).slice(0,f.kind==="date"?10:16);if(Array.isArray(values[f.key]))values[f.key]=values[f.key].join(", ");}setDraft(values);setNotice("");};
 const save=async()=>{
   if(!client)return;
   const missing=module.fields.find(f=>f.required&&(draft[f.key]===undefined||draft[f.key]===null||String(draft[f.key]).trim()===""));
   if(missing){setNotice(`${missing.label} is required.`);return;}
   setSaving(true);setNotice("");
   const payload:Record<string,any>={};
   for(const f of module.fields){let value=draft[f.key];if(value===""||value===undefined)value=null;if(value!==null&&["teaching_areas","research_areas"].includes(f.key))value=String(value).split(",").map((x:string)=>x.trim()).filter(Boolean);if(value!==null&&f.kind==="number")value=Number(value);if(value!==null&&f.kind==="datetime")value=new Date(value).toISOString();payload[f.key]=value;}
   if(module.status&&payload.status==="published"&&!payload.published_at&&module.fields.some(f=>f.key==="published_at"))payload.published_at=new Date().toISOString();
   if(slugFields.has(module.table)&&!payload.slug)payload.slug=toSlug(String(payload[module.titleField]??""));
   if(module.table==="specializations"&&!payload.slug)payload.slug=toSlug(String(payload.name??""));
   if(module.table==="departments"&&!payload.slug)payload.slug=toSlug(String(payload.name??""));
   if(module.table==="faculty_information"&&typeof payload.content==="string"){try{payload.content=JSON.parse(payload.content||"{}");}catch{setNotice("Content must be valid JSON.");setSaving(false);return;}}
   const query=editing?.id?client.from(module.table as any).update(payload).eq("id",editing.id):client.from(module.table as any).insert(payload);
   const {error}=await query;
   if(error)setNotice(`Save failed: ${error.message}`);else{setNotice("Saved successfully.");setEditing(null);setDraft({});await loadRows();await loadRelations();}
   setSaving(false);
 };
 const remove=async(row:any,target:Module=module)=>{if(!client||!window.confirm(`Delete “${row[target.titleField]??row.id}”? This cannot be undone.`))return;const {error}=await client.from(target.table as any).delete().eq("id",row.id);setNotice(error?`Delete failed: ${error.message}`:"Record deleted.");if(!error){if(globalSearch)setGlobalRows(prev=>prev.filter(x=>!(x.id===row.id&&x._moduleKey===target.key)));await loadRows();}};
 const publicHref=(row:any,target:Module=module)=>{
   const department=departments.find(d=>d.id===row.department_id);
   if(target.key==="departments")return `/departments/${row.slug}`;
   if(target.key==="specializations")return `/departments/${department?.slug??""}/specialties/${row.slug}`;
   if(department&&["programs","research","news","events","gallery","documents"].includes(target.key))return `/departments/${department.slug}/${target.key}/${row.slug||row.id}`;
   if(target.key==="timetables"&&department)return `/departments/${department.slug}/timetables`;
   return row.slug?`${target.route}/${row.slug}`:target.route;
 };
 const relationLabel=(table:string,item:any)=>table==="timetables"?`${item.level} · ${item.semester} · ${item.academic_year} (${departments.find(d=>d.id===item.department_id)?.name??"Faculty"})`:item[relationLabels[table]];
 const uploadFile=async(field:Field,file?:File)=>{
   if(!client||!file)return;
   const isImage=field.key==="image_path";
   if(file.size>20*1024*1024){setNotice("Files must be 20 MB or smaller.");return;}
   if(isImage&&!(["image/jpeg","image/png","image/webp"].includes(file.type))){setNotice("Choose a JPEG, PNG or WebP image.");return;}
   setSaving(true);setNotice("");
   const safe=file.name.toLowerCase().replace(/[^a-z0-9._-]+/g,"-");
   const path=`${module.table}/${Date.now()}-${safe}`;
   const {error}=await client.storage.from("faculty-public").upload(path,file,{upsert:false,contentType:file.type});
   if(error)setNotice(`Upload failed: ${error.message}`);else{const url=client.storage.from("faculty-public").getPublicUrl(path).data.publicUrl;setValue(field.key,url);if(module.table==="documents"){setValue("mime_type",file.type);setValue("file_size_bytes",file.size);}setNotice("File uploaded. Save the record to publish it.");}
   setSaving(false);
 };
 const fieldControl=(field:Field)=>{
   const value=draft[field.key]??(field.kind==="boolean"?false:"");
   if((field.key==="image_path"&&["departments","specializations","programs","gallery","news","events","research"].includes(module.key))||(field.key==="storage_path"&&module.key==="documents"))return <div className="upload-control"><input type="file" accept={field.key==="image_path"?"image/jpeg,image/png,image/webp":"application/pdf,image/jpeg,image/png,image/webp"} onChange={e=>uploadFile(field,e.target.files?.[0])}/>{value&&<small>File selected: <a href={value} target="_blank" rel="noreferrer">Preview current file</a></small>}<input aria-label={field.label+" URL"} value={value} onChange={e=>setValue(field.key,e.target.value)} placeholder="Or paste a public URL"/></div>;
   if(field.relation){const opts=relations[field.relation]??[];const filtered=field.relation==="specializations"&&draft.department_id?opts.filter(x=>x.department_id===draft.department_id):field.relation==="programs"&&draft.department_id?opts.filter(x=>x.department_id===draft.department_id):opts;return <select value={value} onChange={e=>{setValue(field.key,e.target.value);if(field.key==="department_id"){setValue("specialization_id","");if(module.key==="timetables")setValue("program_id","");}if(field.key==="specialization_id"){const chosen=opts.find(x=>x.id===e.target.value);if(chosen?.department_id)setValue("department_id",chosen.department_id);}}}><option value="">— Select —</option>{filtered.map(x=><option key={x.id} value={x.id}>{relationLabel(field.relation!,x)}{x.department_id&&field.relation==="specializations"?` · ${departments.find(d=>d.id===x.department_id)?.name??""}`:""}</option>)}</select>;}
   if(field.kind==="boolean")return <input type="checkbox" checked={!!value} onChange={e=>setValue(field.key,e.target.checked)}/>;
   if(field.kind==="select")return <select value={value} onChange={e=>setValue(field.key,e.target.value)}>{(field.options??[]).map(x=><option key={x}>{x}</option>)}</select>;
   if(field.kind==="textarea")return <textarea rows={field.key==="body"||field.key==="details"||field.key==="content"?6:3} value={typeof value==="object"?JSON.stringify(value,null,2):value} onChange={e=>setValue(field.key,e.target.value)}/>;
   return <input type={field.kind==="number"?"number":field.kind==="date"?"date":field.kind==="datetime"?"datetime-local":"text"} value={value} required={field.required} onChange={e=>setValue(field.key,e.target.value)}/>;
 };
 const visibleRows=(globalSearch?globalRows:scopedRows).filter(row=>{const id=row.department_id??row.timetable?.department_id;return !departmentId||!id||id===departmentId;}).filter(row=>{const id=row.specialization_id??row.timetable?.specialization_id;return !specialtyId||!id||id===specialtyId;});
 return <div className="admin-workspace"><aside className="admin-sidebar"><div className="admin-side-heading"><LayoutDashboard size={18}/><div><strong>Faculty CMS</strong><small>Content workspace</small></div></div><button className="admin-side-item" onClick={()=>{setActive("departments");setDepartmentId("");setSpecialtyId("");}}><FolderTree size={16}/> Overview</button><span className="admin-side-label">FACULTY CONTENT</span>{modules.map(m=><button key={m.key} className={`admin-side-item ${active===m.key?"active":""}`} onClick={()=>setActive(m.key)}>{m.label}</button>)}</aside>
 <div className="admin-main"><div className="admin-topbar"><div><p className="section-kicker">Content management</p><h1>Welcome, {displayName}</h1><div className="hierarchy-trail"><span>FACULTY</span><ChevronRight size={13}/><select aria-label="Filter by department" value={departmentId} onChange={e=>{setDepartmentId(e.target.value);setSpecialtyId("");}}><option value="">All departments</option>{departments.map(d=><option value={d.id} key={d.id}>{d.name}</option>)}</select>{departmentId&&<><ChevronRight size={13}/><select aria-label="Filter by specialty" value={specialtyId} onChange={e=>setSpecialtyId(e.target.value)}><option value="">All specialties</option>{specialties.filter(s=>s.department_id===departmentId).map(s=><option value={s.id} key={s.id}>{s.name}</option>)}</select></>}</div></div><div className="admin-top-actions"><Link href="/" target="_blank" className="text-link"><Eye size={15}/> View site</Link><button className="button button-primary" onClick={createRecord}><FilePlus2 size={15}/> New {({faculty:"faculty information",departments:"department",specializations:"specialty",programs:"programme",research:"research project",news:"news item",events:"event",gallery:"gallery image",documents:"document",timetables:"timetable",timetable_entries:"timetable class"} as Record<string,string>)[module.key]}</button></div></div>
 <div className="admin-toolbar"><div className="admin-search"><Search size={16}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder={`Search ${globalSearch?"all faculty content":module.label.toLowerCase()}…`} /></div><button className={`search-mode ${globalSearch?"active":""}`} onClick={()=>setGlobalSearch(v=>!v)}><Search size={13}/> Global search</button><span>{visibleRows.length} record{visibleRows.length===1?"":"s"}</span>{module.context&&departmentId&&<span className="context-badge">{departments.find(d=>d.id===departmentId)?.name}{specialtyId ? ` · ${specialties.find(s=>s.id===specialtyId)?.name??""}` : ""}</span>}</div>
 {notice&&<p className={`admin-notice ${notice.includes("failed")||notice.includes("Cannot")?"is-error":"is-success"}`}>{notice}</p>}
 <div className="admin-content-grid"><section className="admin-records">{loading?<div className="admin-loading"><LoaderCircle className="spin"/> Loading records…</div>:visibleRows.length?visibleRows.map(row=>{const recordModule=modules.find(m=>m.key===row._moduleKey)??module;return <article className={`admin-record ${editing?.id===row.id?"selected":""}`} key={`${recordModule.key}-${row.id}`}><div className="admin-record-copy"><span className="section-kicker">{recordModule.label}</span><span className={`status-pill status-${row.status??(row.is_active?"active":"inactive")}`}>{row.status??(row.is_active?"active":"inactive")}</span><h2>{row[recordModule.titleField]||row.title||row.key||"Untitled record"}</h2><p>{row.description||row.summary||row.excerpt||row.degree||row.semester||row.key||"No summary"}</p><small>{(row.department_id??row.timetable?.department_id)?departments.find(d=>d.id===(row.department_id??row.timetable?.department_id))?.name:"Faculty-wide"}{(row.specialization_id??row.timetable?.specialization_id) ? ` · ${specialties.find(s=>s.id===(row.specialization_id??row.timetable?.specialization_id))?.name??""}` : ""}</small></div><div className="admin-record-actions">{row.slug&&(row.status==="published"||row.is_active)&&<Link href={publicHref(row,recordModule)} target="_blank" aria-label="Preview published record"><ArrowUpRight size={16}/></Link>}<button onClick={()=>editRecord(row,recordModule)}>Edit</button><button className="delete-action" onClick={()=>remove(row,recordModule)} aria-label="Delete record"><Trash2 size={15}/></button></div></article>;}):<div className="admin-empty"><FolderTree size={27}/><h2>No records found</h2><p>Create content here or adjust your department, specialty and search filters.</p><button className="button button-primary" onClick={createRecord}><FilePlus2 size={15}/> Create {({faculty:"faculty information",departments:"department",specializations:"specialty",programs:"programme",research:"research project",news:"news item",events:"event",gallery:"gallery image",documents:"document",timetables:"timetable",timetable_entries:"timetable class"} as Record<string,string>)[module.key]}</button></div>}</section>
 <aside className="admin-preview"><div className="preview-heading"><div><p className="section-kicker">Live structure</p><h2>Faculty hierarchy</h2></div><FolderTree size={19}/></div><div className="hierarchy-tree"><strong>FACULTY OF SCIENCE</strong>{(departmentId?departments.filter(d=>d.id===departmentId):departments).map(d=><div className="tree-dept" key={d.id}><span>↳ {d.name}</span>{specialties.filter(s=>s.department_id===d.id).map(s=><small key={s.id}>↳ {s.name}</small>)}</div>)}</div><div className="preview-content"><p className="section-kicker"><Eye size={13}/> PUBLIC DESTINATION</p>{editing? <><h3>{draft[module.titleField]||"New content preview"}</h3><p>{draft.excerpt||draft.summary||draft.description||"Your changes will appear here when published."}</p><span className="status-pill status-draft">{draft.status||"draft"}</span></>:<><h3>{active==="departments"?"Department pages":module.label}</h3><p>Published records appear on the matching public page and are linked from their department or specialty.</p></>}<Link className="text-link" href={editing?.slug?publicHref(editing):module.route} target="_blank">Open public section <ArrowUpRight size={14}/></Link></div></aside></div>
 {editing!==null&&<div className="admin-editor-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget){setEditing(null);setDraft({});}}}><section className="admin-editor" aria-label="Edit content"><div className="editor-heading"><div><p className="section-kicker">{editing.id?"Edit record":"Create record"}</p><h2>{editing.id?editing[module.titleField]||"Update content":`New ${module.label.toLowerCase()}`}</h2></div><button onClick={()=>{setEditing(null);setDraft({});}} aria-label="Close editor">×</button></div><p className="editor-context">FACULTY <ChevronRight size={12}/>{departmentId?departments.find(d=>d.id===departmentId)?.name:"All departments"}{specialtyId?<> <ChevronRight size={12}/>{specialties.find(s=>s.id===specialtyId)?.name}</>:null}</p><div className="editor-fields">{module.fields.map(field=><label className={field.kind==="boolean"?"checkbox-field":""} key={field.key}><span>{field.label}{field.required&&<b> *</b>}</span>{fieldControl(field)}</label>)}</div><div className="editor-preview"><p className="section-kicker">Preview</p><h3>{draft[module.titleField]||"Content title"}</h3><p>{draft.excerpt||draft.summary||draft.description||"Add a short description to preview this content."}</p><span className="status-pill status-draft">{draft.status||"draft"}</span><small>Will appear in {module.route} and related department/specialty pages.</small></div>{notice&&<p className="admin-notice is-error">{notice}</p>}<div className="editor-actions"><button className="button button-quiet" onClick={()=>{setEditing(null);setDraft({});}}>Cancel</button><button className="button button-primary" disabled={saving} onClick={save}>{saving?<LoaderCircle className="spin" size={15}/>:<Check size={15}/>} {saving?"Saving…":"Save content"}</button></div></section></div>}
 </div></div>;
}
