import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowRight, ArrowUpRight, BookOpen, FlaskConical, Images, Newspaper, FileText } from "lucide-react";
import { createPublicClient } from "@/lib/supabase/public";
import { TimetableSearch } from "@/app/timetables/timetable-search";
import { DEPARTMENT_FALLBACKS } from "@/lib/content";
import { PublicPageBlocks } from "@/components/public-page-blocks";

export const dynamic = "force-dynamic";
const sections:Record<string,{table:string;title:string;titleField:string;bodyField:string;image?:boolean;file?:boolean}>={
  programs:{table:"programs",title:"Programs",titleField:"name",bodyField:"description",image:true},
  research:{table:"research_projects",title:"Department research",titleField:"title",bodyField:"summary",image:true},
  "news-events":{table:"news",title:"News & Events",titleField:"title",bodyField:"excerpt",image:true},
  news:{table:"news",title:"News",titleField:"title",bodyField:"excerpt",image:true},
  events:{table:"events",title:"Events",titleField:"title",bodyField:"description",image:true},
  gallery:{table:"gallery_items",title:"Gallery",titleField:"title",bodyField:"description",image:true},
  documents:{table:"documents",title:"Documentation",titleField:"title",bodyField:"description",file:true},
};

export default async function DepartmentSectionPage({params,searchParams}:{params:Promise<{slug:string;section:string}>;searchParams:Promise<{specialty?:string}>}){
  const {slug,section}=await params;const selected=await searchParams;const client=createPublicClient();
  const {data:liveDepartment}=client?await client.from("departments").select("*").eq("slug",slug).eq("is_active",true).maybeSingle():{data:null};
  const department=liveDepartment??DEPARTMENT_FALLBACKS.find(x=>x.slug===slug);if(!department)notFound();
  if(section==="timetables")return <><section className="page-hero"><div className="wrap"><p className="section-kicker"><Link href={`/departments/${slug}`}>{department.name}</Link> · Student services</p><h1>{department.name} timetables</h1><p>Choose a specialty, level, semester and academic year to view or download the matching timetable.</p></div></section><section className="content-section"><div className="wrap"><TimetableSearch initialDepartment={department.id||""} initialSpecialty={selected.specialty??""}/></div></section></>;
  if(section==="specialties"||section==="specializations"){
    const {data:specialties}=client&&department.id?await client.from("specializations").select("*").eq("department_id",department.id).eq("is_active",true).order("sort_order").order("name"):({data:[]});
    return <><section className="page-hero"><div className="wrap"><p className="section-kicker"><Link href={`/departments/${slug}`}>{department.name}</Link> · Areas of study</p><h1>{department.name} specialties</h1><p>Explore the fields of study, learning objectives and career pathways offered by this department.</p></div></section><section className="content-section"><div className="wrap"><div className="department-section-nav">{["programs","research","news-events","gallery","documents","timetables"].map(key=><Link key={key} href={`/departments/${slug}/${key}`}>{key.replace("-"," & ")}</Link>)}</div><div className="section-head-row"><div><p className="section-kicker">Study areas · {department.name}</p><h2 className="section-heading">Find your specialty.</h2></div></div>{specialties?.length?<div className="department-feature-grid">{specialties.map((item:any)=><article className="department-feature-card" key={item.id}><Link className="department-feature-media" href={`/departments/${slug}/specialties/${item.slug}`}>{item.image_path?<img src={item.image_path} alt={item.name}/>:<span className="department-media-placeholder"><Images size={28}/> Specialty image</span>}</Link><div className="department-feature-copy"><p className="section-kicker">{department.name} · Specialty</p><h2>{item.name}</h2><p>{item.description||item.mission||"A dedicated learning and research pathway within this department."}</p>{item.objectives&&<p><strong>Objectives:</strong> {item.objectives}</p>}<Link className="text-link" href={`/departments/${slug}/specialties/${item.slug}`}>Discover this specialty <ArrowRight size={14}/></Link></div></article>)}</div>:<EmptySection title="Specialty profiles are ready to be added" description="Specialties created for this department will appear here with a full profile, image, programmes, research and learning resources." icon="specialties"/>}<div className="department-promo-grid"><article><p className="section-kicker">Learning outcomes</p><h3>Build a pathway in {department.name}</h3><p>Each specialty profile includes objectives, teaching areas, research and career information.</p></article><article><p className="section-kicker">Continue exploring</p><h3>Programmes and research</h3><p>Browse department programmes and research or open a specialty for content linked specifically to that field.</p><Link className="text-link" href={`/departments/${slug}/programs`}>Explore programmes <ArrowRight size={14}/></Link></article></div></div></section></>;
  }
  const config=sections[section];if(!config)notFound();if(!client||!department.id)return <><section className="page-hero"><div className="wrap"><p className="section-kicker"><Link href={`/departments/${slug}`}>{department.name}</Link> · Department resources</p><h1>{config.title} · {department.name}</h1><p>This department section is ready for its content to be published.</p></div></section><section className="content-section"><div className="wrap"><EmptySection title={`${config.title} will appear here`} description={`The ${department.name} ${config.title.toLowerCase()} page is ready for department content.`} icon={section}/></div></section></>;
  const [{data:specialties},{data:rowsResult},{data:albumsResult}]=await Promise.all([
    client.from("specializations").select("id,name,slug").eq("department_id",department.id).eq("is_active",true).order("name"),
    (async()=>{
      if(section==="news-events"){
        let newsQuery=client.from("news").select("*,specialty:specializations(name,slug)").eq("department_id",department.id).eq("status","published");
        let eventsQuery=client.from("events").select("*,specialty:specializations(name,slug)").eq("department_id",department.id).eq("status","published");
        if(selected.specialty){newsQuery=newsQuery.eq("specialization_id",selected.specialty);eventsQuery=eventsQuery.eq("specialization_id",selected.specialty);}
        const [newsResult,eventResult]=await Promise.all([newsQuery.order("published_at",{ascending:false}),eventsQuery.order("starts_at",{ascending:false})]);
        return {data:[...(newsResult.data??[]).map(item=>({...item,_kind:"news"})),...(eventResult.data??[]).map(item=>({...item,_kind:"events"}))].sort((a,b)=>String(b.published_at||b.starts_at||"").localeCompare(String(a.published_at||a.starts_at||"")))};
      }
      let query=client.from(config.table).select("*,specialty:specializations(name,slug)").eq("department_id",department.id);
      if(selected.specialty)query=query.eq("specialization_id",selected.specialty);
      if(section==="programs")return await query.eq("is_active",true).order("name");
      return await query.in("status",section==="research"?["published","completed"]:["published"]).order("created_at",{ascending:false});
    })(),
    section==="gallery"?client.from("gallery_albums").select("*,specialty:specializations(name,slug)").eq("department_id",department.id).eq("status","published").then(result=>result):Promise.resolve({data:[] as any[]}),
  ]);
  let rows:any[]=rowsResult??[];
  if(section==="gallery")rows=[...(albumsResult??[]).map((album:any)=>({...album,_album:true})),...rows];
  const activeSpecialty=specialties?.find((item:any)=>item.id===selected.specialty);
  const title=activeSpecialty?`${config.title} · ${activeSpecialty.name}`:`${config.title} · ${department.name}`;
  const navKeys=["specialties","programs","research","news-events","gallery","documents","timetables"];
  return <><section className="page-hero"><div className="wrap"><p className="section-kicker"><Link href={`/departments/${slug}`}>{department.name}</Link> · Department resources</p><h1>{title}</h1><p>{section==="research"?`Research axes, teams, laboratories and projects across ${department.name}. Specialty-specific projects are identified below.`:section==="programs"?`Explore study programmes, cycles and levels${activeSpecialty?` associated with ${activeSpecialty.name}`:` offered by ${department.name}`}.`:section==="news-events"?`News stories and upcoming events from ${activeSpecialty?.name??department.name}.`:section==="gallery"?`Albums and images from teaching, research and events in ${activeSpecialty?.name??department.name}.`:section==="documents"?`Guides, notices and academic documents for ${activeSpecialty?.name??department.name}.`:`Browse ${config.title.toLowerCase()} from this department.`}</p></div></section><section className="content-section"><div className="wrap"><nav className="department-section-nav" aria-label="Department sections">{navKeys.map(key=><Link key={key} className={key===section?"active":""} href={`/departments/${slug}/${key}`}>{key==="news-events"?"News & Events":key==="documents"?"Documentation":key.charAt(0).toUpperCase()+key.slice(1)}</Link>)}</nav>
    {specialties?.length>0&&<form className="department-specialty-filter" method="get"><label htmlFor="specialty-filter">Filter by specialty</label><select id="specialty-filter" name="specialty" defaultValue={selected.specialty??""}><option value="">All department content</option>{specialties.map((item:any)=><option key={item.id} value={item.id}>{item.name}</option>)}</select><button className="button button-primary" type="submit">Filter content</button>{selected.specialty&&<Link className="text-link" href={`/departments/${slug}/${section}`}>Clear filter</Link>}</form>}
    {section==="research"&&<div className="department-promo-grid"><article><p className="section-kicker">Research axes</p><h3>Questions shaping our work</h3><p>Research areas and current projects are managed by department and specialty.</p></article><article><p className="section-kicker">Teams & laboratories</p><h3>People behind the research</h3><p>Find lead researchers, teams, laboratories and publications in each project profile.</p></article></div>}
    {rows.length?<div className="department-feature-grid">{rows.map((row:any)=>{const kind=row._kind||section;const itemTitle=row._album?row.title:row[config.titleField];const destination=row._album?`/departments/${slug}/gallery/albums/${row.slug}`:`/departments/${slug}/${kind}/${row.slug||row.id}`;const image=row._album?row.cover_image_path:row.image_path;const summary=row._album?row.description:row[config.bodyField]||row.body||row.excerpt||row.summary;return <article className="department-feature-card" key={`${kind}-${row.id}`}><Link className="department-feature-media" href={destination}>{config.image&&image?<img src={image} alt={itemTitle}/>:<span className="department-media-placeholder">{section==="programs"?<BookOpen size={28}/>:section==="research"?<FlaskConical size={28}/>:section==="gallery"?<Images size={28}/>:section==="documents"?<FileText size={28}/>:<Newspaper size={28}/>} Image area · ready for content</span>}</Link><div className="department-feature-copy"><p className="section-kicker">{row.category||row.degree||row.research_axis||row._kind||config.title}{row.specialty?.name?` · ${row.specialty.name}`:""}</p><h2><Link href={destination}>{itemTitle}</Link></h2><p>{summary||`Published ${config.title.toLowerCase()} from ${row.specialty?.name||department.name}.`}</p>{(row.published_at||row.starts_at||row.album_date)&&<p className="resource-context">{new Date(row.published_at||row.starts_at||row.album_date).toLocaleDateString("en",{dateStyle:"long"})}{row.author_name?` · ${row.author_name}`:""}</p>}{row.degree&&<p className="resource-context">{row.degree}{row.cycle?` · ${row.cycle}`:""}{row.level?` · ${row.level}`:""}</p>}{row.research_axis&&<p className="resource-context">Axis: {row.research_axis}{row.laboratory?` · ${row.laboratory}`:""}</p>}{row.storage_path&&<a className="text-link" href={row.external_url||row.storage_path} target="_blank" rel="noreferrer">Consult / download <ArrowUpRight size={14}/></a>}<Link className="text-link" href={destination}>{section==="news-events"?"Read more":row._album?"Open album":section==="documents"?"View document":"Discover"} <ArrowUpRight size={14}/></Link></div></article>;})}</div>:<EmptySection title={`No ${config.title.toLowerCase()} published yet`} description={`This page is built for ${department.name}. When department or specialty content is published, its cards, images and links will appear here.`} icon={section}/>}
    {section==="research"&&rows.some((row:any)=>row.publications?.length>0)&&<section className="department-publications"><p className="section-kicker">Publications</p><h2 className="section-heading">Research outputs</h2><div className="simple-list">{rows.flatMap((row:any)=>row.publications??[]).map((publication:string,index:number)=><article key={`${publication}-${index}`}><p>{publication}</p></article>)}</div></section>}
    <div className="department-section-end"><Link className="text-link" href={`/departments/${slug}`}>Back to {department.name} <ArrowRight size={14}/></Link></div><PublicPageBlocks scope="department" pageKey={`${slug}-${section}`} departmentId={department.id}/></div></section></>;
}

function EmptySection({title,description,icon}:{title:string;description:string;icon:string}){return <div className="department-section-empty"><span className="department-media-placeholder"><Images size={26}/>{icon} image / content area</span><div><p className="section-kicker">Content space</p><h2>{title}</h2><p>{description}</p><div className="empty-content-tiles"><span>Introduction</span><span>Images & media</span><span>Related resources</span></div></div></div>}
